server:
  port: 7000
spring:
  application:
    name: simple4h-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
nacos:
  DATA_ID: gateway-config
  GROUP: DEFAULT_GROUP
management:
  endpoints:
    web:
      exposure:
        include: '*'