spring:
  application:
    name: simple4h-user
  cloud:
    nacos:
      discovery:
        server-addr: nacos.cxm520hyq.com
    sentinel:
      transport:
        dashboard: 127.0.0.1:8843
      datasource:
        flow:
          nacos:
            server-addr: nacos.cxm520hyq.com
            dataId: sentinel-dashboard
            groupId: DEFAULT_GROUP
            rule-type: flow

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'