spring:
  application:
    name: simple4h-product
  cloud:
    nacos:
      discovery:
        server-addr: nacos.cxm520hyq.com
    sentinel:
      transport:
        dashboard: sentinel.cxm520hyq.com
      datasource:
        flow:
          nacos:
            server-addr: nacos.cxm520hyq.com
            dataId: sentinel-dashboard
            groupId: DEFAULT_GROUP
            rule-type: flow
server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: '*'