spring:
  application:
    name: simple4h-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8843
      datasource:
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: sentinel-dashboard
            groupId: DEFAULT_GROUP
            rule-type: flow
server:
  port: 9000